# general settings
name: 009_HAN_x3_AID_100k_B16G1P96
model_type: SRModel
scale: 3
num_gpu: 1
manual_seed: 123
find_unused_parameters: true

# dataset and data loader settings
datasets:
  train:
    name: AID_train
    type: PairedImageDataset
    dataroot_gt: datasets/processed/AID/AID_train_HR
    dataroot_lq: datasets/processed/AID/AID_train_LR_bicubic/X3
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu
    pin_memory: false

    gt_size: 96

  val: # validation dataset
    name: AID_val
    type: PairedImageDataset
    dataroot_gt: datasets/processed/AID/AID_val_HR
    dataroot_lq: datasets/processed/AID/AID_val_LR_bicubic/X3
    io_backend:
      type: disk

# network structures
network_g:
  type: HAN
  scale: 3

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 3e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [30667, 69333]
    restart_weights: [1,1]
    eta_mins: [0.0003,0.000001]

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

  total_iter: 100000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true # False
  pbar: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 3
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 3
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
     project: ~
     resume_id: ~
#    project: SR-models
#    resume_id:
#    entity: rywaii99

# dist training settings
dist_params:
  backend: nccl
  port: 29500