# general settings
name: G01_ESRGAN_x4_AID_300k_B16G1
model_type: ESRGANModel
scale: 4
num_gpu: 1
manual_seed: 123

# dataset and data loader settings
datasets:
  train:
    name: AID_train
    type: PairedImageDataset
    dataroot_gt: datasets/processed/AID/AID_train_HR
    dataroot_lq: datasets/processed/AID/AID_train_LR_bicubic/X4
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_hflip: true
    use_rot: true

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 1
    prefetch_mode: cpu
    pin_memory: false

    gt_size: 128

  val: # validation dataset
    name: AID_val
    type: PairedImageDataset
    dataroot_gt: datasets/processed/AID/AID_val_HR
    dataroot_lq: datasets/processed/AID/AID_val_LR_bicubic/X4
    io_backend:
      type: disk

# network structures
network_g:
  type: RRDBNet
  num_in_ch: 3
  num_out_ch: 3
  num_feat: 64
  num_block: 23

network_d:
  type: VGGStyleDiscriminator
  num_in_ch: 3
  num_feat: 64

# path
path:
  pretrain_network_g: ~
  strict_load_g: false
  resume_state: ~

# training settings
train:
  ema_decay: 0.999
  optim_g:
    type: AdamW
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]
  optim_d:
    type: Adam
    lr: !!float 1e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [ 50000, 100000, 200000, 300000 ]
    gamma: 0.5

  total_iter: 300000
  warmup_iter: -1  # no warm up

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: !!float 1e-2
    reduction: mean
  perceptual_opt:
    type: PerceptualLoss
    layer_weights:
      'conv5_4': 1  # before relu
    vgg_type: vgg19
    use_input_norm: true
    range_norm: false
    perceptual_weight: 1.0
    style_weight: 0
    criterion: l1
  gan_opt:
    type: GANLoss
    gan_type: vanilla
    real_label_val: 1.0
    fake_label_val: 0.0
    loss_weight: !!float 5e-3

  net_d_iters: 1
  net_d_init_iters: 0

# validation settings
val:
  val_freq: !!float 1e4
  save_img: true # False
  pbar: false

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: false
      better: higher  # the higher, the better. Default: higher
    fid:
      type: calculate_fid
      crop_border: 4
      test_y_channel: false
      better: lower
    lpips:
      type: calculate_lpips
      crop_border: 4
      test_y_channel: false
      better: lower

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
     project: ~
     resume_id: ~
#    project: SR-models
#    resume_id:
#    entity: rywaii99

# dist training settings
dist_params:
  backend: nccl
  port: 29500